<?php
/**
 * @file
 * Created by Ivan levmyshkin Abramenko
 * http://site-made.ru
 * Skype: Abramenko89
 * Email: levmyshkin89@gmail.com
 * Feel free for write me question/issues about this drupal installation
 */

/**
 * Implements hook_init().
 */
function uc_multivendor_init() {
  drupal_add_library('system', 'ui.tabs');
  drupal_add_css(drupal_get_path('module', 'uc_multivendor') . '/uc_multivendor.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
}

/**
 * implements hook_menu().
 */
function uc_multivendor_menu() {
  $items = array();

  $items['user/%/list-messages'] = array(
    'title' => t('List of messages'),
    'description' => t('Messages with user'),
    'page callback' => '_uc_multivendor_list_messages',
    'page arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('access content'),
    'expanded' => TRUE,
  );

  return $items;
}

/**
 * Implements hook_block_info().
 */
function uc_multivendor_block_info() {
  $block[1]['info'] = t('Author pane');
  $block[2]['info'] = t('Site statistics');
  return $block;
}

/**
 * Implements hook_block_view().
 */
function uc_multivendor_block_view($delta = '') {
  switch ($delta) {
    case 1:
      $content = '';
      global $user;
      $freinds = db_select('user_relationships', 'r')
        ->condition('requester_id', $user->uid)
        ->condition('rtid', 1)
        ->condition('approved', 1)
        ->countQuery()
        ->execute()
        ->fetchField();
      $messages = db_select('pm_index', 'm')
        ->condition('recipient', $user->uid)
        ->condition('deleted', 0)
        ->condition('type', 'user')
        ->countQuery()
        ->execute()
        ->fetchField();
      $track = views_get_view_result('custom_tracker_new_count', $reset = FALSE);
      $content .= '<div>' . l(t('Friends (') . $freinds . ')', 'user/' . $user->uid . '/relationships') . '</div>';
      $content .= '<div>' . l(t('Messages (') . $messages . ')', 'messages/list') . '</div>';
      $content .= '<div>' . l(t('Discussions (') . count($track) . ')', 'user/' . $user->uid . '/new') . '</div>';
      $block['content'] = $content;
      $block['subject'] = '';
      break;
    case 2:
      $content = '';
      $users = db_select('users', 'u')
        ->countQuery()
        ->execute()
        ->fetchField();
      $time = time() - 1200;
      $online = db_select('users')
        ->condition('access', $time, '>')
        ->countQuery()
        ->execute()
        ->fetchField();
      $products = db_select('node', 'n')
        ->condition('type', 'product')
        ->countQuery()
        ->execute()
        ->fetchField();
      $comments = db_select('comment', 'c')
        ->countQuery()
        ->execute()
        ->fetchField();
      $content .= '<div>' . t('Users online:') . '<strong>' . $online . '</strong></div>';
      $content .= '<div>' . t('Total users:') . '<strong>' . $users . '</strong></div>';
      $content .= '<div>' . t('Total products:') . '<strong>' . $products . '</strong></div>';
      $content .= '<div>' . t('Total comments:') . '<strong>' . $comments . '</strong></div>';
      $block['content'] = $content;
      $block['subject'] = t('Site statistics');
      break;
  }
  return $block;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function uc_multivendor_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  if (arg(0) == 'user' && is_numeric(arg(1))) {
    if (!empty($data['tabs'][0])) {
      foreach ($data['tabs'][0]['output'] as $key => $tab) {
        if ($tab['#link']['path'] == 'user/%/track') {
          unset($data['tabs'][0]['output'][$key]);
          $data['tabs'][0]['count']--;
        }
      }
      foreach ($data['tabs'][0]['output'] as $key => $tab) {
        if ($tab['#link']['path'] == 'user/%/shortcuts') {
          unset($data['tabs'][0]['output'][$key]);
          $data['tabs'][0]['count']--;
        }
      }
      foreach ($data['tabs'][0]['output'] as $key => $tab) {
        if ($tab['#link']['path'] == 'user/%/bookmarks') {
          unset($data['tabs'][0]['output'][$key]);
          $data['tabs'][0]['count']--;
        }
      }
      foreach ($data['tabs'][0]['output'] as $key => $tab) {
        if ($tab['#link']['path'] == 'user/%/imce') {
          unset($data['tabs'][0]['output'][$key]);
          $data['tabs'][0]['count']--;
        }
      }
    }
  }
}

/*
 * $uid - id who writes me.
 */
function _uc_multivendor_list_messages($uid) {
  global $user;
  if (!$user->uid) {
    return l(t('Login'), 'user') . t(', for talking with your friends');
  }
  if ($user->uid == $uid) {
    return t('Come in private messages');
  }
  $query = db_select('pm_message', 'm');
  $query->innerJoin('pm_index', 'i', 'm.mid=i.mid');
  $query->fields('m');
  $query->fields('i');
  $query->condition('m.author', $uid);
  $query->condition('i.recipient', $user->uid);
  $list1 = $query->execute()->fetchAll();  //incoming
  $query = db_select('pm_message', 'm');
  $query->innerJoin('pm_index', 'i', 'm.mid=i.mid');
  $query->fields('m');
  $query->fields('i');
  $query->condition('m.author', $user->uid);
  $query->condition('i.recipient', $uid);
  $list2 = $query->execute()->fetchAll();  //outcoming
  $list = array_merge($list1, $list2);
  usort($list, "uc_multivendor_cmp");
  $content = '';
  $user1 = user_load($user->uid);
  $user2 = user_load($uid);
  $content .= '<a class="send-message" href="/messages/new/' . $uid . '?destination=user/' . $uid . '/list-messages">Написать сообщение</a>';
  foreach ($list as $message) {
    if ($message->author == $user->uid) { //user1
      $content .= '<div class="user1 user-message">';

      $content .= '<div class="time"> ' . $user1->name . ' - ' . date("d.m.Y H:i:s", $message->timestamp) . '</div>';
      $content .= '<div class="body">' . $message->body . '</div>';
      $content .= '</div>';
    }
    else {
      $content .= '<div class="user2 user-message">';
      $content .= '<div class="time"> ' . $user2->name . ' - ' . date("d.m.Y H:i:s", $message->timestamp) . '</div>';
      $content .= '<div class="body">' . $message->body . '</div>';
      $content .= '</div>';
    }
  }
  if (empty($list)) {
    $content .= '<div>' . t('You have no messages from this user') . '</div>';
  }
  $content .= '<a class="send-message" href="/messages/new/' . $uid . '?destination=user/' . $uid . '/list-messages">' . t('write message') . '</a>';
  return $content;
}

/**
 * Sort array by timestamp.
 */
function uc_multivendor_cmp($a, $b) {
  return strcmp($b->timestamp, $a->timestamp);
}

